[build]
command = "npm run build"
publish = "dist"

[[headers]]
for = "/assets/*"
[headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.html"
[headers.values]
  Cache-Control = "public, max-age=0, must-revalidate"
